# BlurMyCLI config

# Keyboard
input {
    kb_layout = de
}  

# defines
$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$appLauncher = __CLI_LAUNCH_PATH__
$searchBar = __CLI_SEARCH_PATH__
$menu = __CLI_MENU_PATH__

# autostart
exec-once = hyprsunset &

# windowrules
windowrule = match:class ^(cli-launch)$, float on, center on, size 800 600, border_size 0, rounding 0
windowrule = match:class ^(cli-search)$, float on, center on, size 500 50, border_size 0, rounding 0
windowrule = match:class ^(cli-menu)$, float on, center on, size 800 600, border_size 0, rounding 0
windowrule = match:workspace name:minimized, tile on

# binds
bind = $mainMod, S, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, Space, exec, kitty --class cli-launch --title cli-launch -e $appLauncher
bind = $mainMod, Y, exec, zen-browser
bind = $mainMod SHIFT, Space, exec, kitty --class cli-search --title cli-search -e $searchBar
bind = $mainMod ALT, Space, exec, kitty --class cli-menu --title cli-menu -e $menu
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d
bind = $mainMod SHIFT, left, movewindow, l
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, up, movewindow, u
bind = $mainMod SHIFT, down, movewindow, d
bind = $mainMod SHIFT, h, movewindow, l
bind = $mainMod SHIFT, l, movewindow, r
bind = $mainMod SHIFT, k, movewindow, u
bind = $mainMod SHIFT, j, movewindow, d
bind = $mainMod, N, movetoworkspacesilent, special:minimized
bind = $mainMod, B, togglespecialworkspace, minimized
bind = $mainMod SHIFT, B, movetoworkspace, +0

# animation
bezier= b0,0,1,0,1.05
bezier= b1,0,1.1,0,1.05
animation = windows,1,4,b1,slide
animation = windowsIn,1,4,b0,popin 88%
animation = windowsOut,1,4,b0,slide
animation = workspaces,1,3,default,slide

# deco(e.g. blur)
decoration {
    blur {
        enabled = true
        size = 8
        passes = 2
        ignore_opacity = true
        new_optimizations = true
        xray = false
        noise = 0.01
        contrast = 0.90
        brightness = 0.85
        vibrancy = 0.18
        vibrancy_darkness = 0.0
        popups = true
    }
    dim_special = 0.0
}
